Repository crossplane-contrib/provider-upjet-azure, pull requests merged in 2022-11, with the labels that each got.

#67 dockerfile: disable terraform user agent
  cluster/images/provider-azure/Dockerfile
Labels: size/XS, backport release-0.18

#75 Fix Uptest timeout annotation
  examples/streamanalytics/analyticscluster.yaml
Labels: size/XS

#73 Configurable maxConcurrentReconciles and pollInterval with sensible defaults
  cmd/provider/main.go
Labels: size/S
